development:
  adapter: mysql2
  encoding: utf8
  database: cloud_chamber
  pool: 20
  username: root
  password: k220jk220j@
  port: 3306
  timeout: 5000
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: cloud_chamber
  pool: 20
  username: root
  password: k220jk220j@
  port: 3306
  timeout: 5000
  host: localhost

production_slave:
  adapter: mysql2
  encoding: utf8
  database: cloud_chamber
  pool: 20
  username: root
  password: k220jk220j@
  port: 3306
  timeout: 5000
  host: localhost
